version: '3'

services:
  mysql1:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=student
      - MYSQL_DATABASE=studentmakers
      - MYSQL_USER=root
      - MYSQL_PASSWORD=student
    restart: unless-stopped
  
  mongodboptimist:
    image: mongo:latest
    container_name: mongostudentmakers
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=studentmakerservice
    volumes:
      - /home/drowen/api/studentmakers/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  studentmaker:
    image: studentmaker
    container_name: studentmakers
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql1

